using System;
using System.Collections;
using System.Collections.Generic;

using Cinemachine;
using UnityEngine;
using static Constants;

public class EncounterManager : MonoBehaviour
{
    [Header("Setup Data")]
    [SerializeField] private EncounterSetupData _setupData; //setup data

    private bool _busy = false;

    private Encounter _encounter; //generated by manager

    private void Update()
    {
        if(Input.GetKeyDown(KeyCode.Space) && !_busy)
        {
            ProcessUpdate();
        }
    }

    private void ProcessUpdate()
    {
        _busy = true;

        //cant update anything if the encounter hasnt been setup!
        if (_encounter == null)
        {
            if(_setupData != null)
            {
                _encounter = _setupData.gameObject.AddComponent<Encounter>();
                _encounter.Setup(_setupData);
            }
            else
            {
                Debug.Log("No setup data to use!");
            }
        }
        else if(!_busy)
        {
            Debug.Log("nothing to do!");
        }
    }
}
