using System;
using System.Collections;
using System.Collections.Generic;

using Cinemachine;
using UnityEngine;
using static Constants;

public class EncounterManager : MonoBehaviour
{
    [Header("Setup Data")]
    [SerializeField] private EncounterSetupData _setupData; //setup data

    [SerializeField] private Encounter _encounter; //generated by manager

    private bool _allowInput = false;

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.Space))
        {
            if (_encounter != null && _allowInput)
            {
                _encounter.TransitionState();
            }
            else
            {
                LoadEncounter();
            }
        }
    }

    public void LoadEncounter()
    {
        _encounter = _setupData.gameObject.AddComponent<Encounter>();
        _encounter.OnStateChanged += EncounterStateCallback;
        _encounter.SetSetupData(_setupData);
        _allowInput = true;
        Debug.Log("Encounter loaded: " + _encounter.name);
    }

    private void EncounterStateCallback(EncounterState state)
    {
    }
}
